@startuml movie
autonumber



'define the icon User
actor User


'define colors
participant API #orange
participant MovieAPI #cyan

'group service
'Start Movie
group controller
User -[#red]> API: (/movie/) Request
end
group service
API -[#red]> MovieAPI: ( getLatestMovie()) Request
API <[#blue]- MovieAPI: ( getLatestMovie()) Response (lastMovie))
end
group controller
User <[#blue]- API: (/movie/) Response (lastMovie)

User -[#red]> API: ( /movie/{movieId}/recommendations) Request(movieId)
end
group service
API -[#red]> MovieAPI: ( getMovieRecommendationsSimilar(movieId, Constants.ENDPOINT_RECOMMENDATIONS)) Request
API <[#blue]- MovieAPI: ( getMovieRecommendationsSimilar(movieId, Constants.ENDPOINT_RECOMMENDATIONS)) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie/{movieId}/recommendations) Response(List<Movie>)
User -[#red]> API: ( /movie/{movieId}/similar) Request(movieId)
end
group service
API -[#red]> MovieAPI: ( getMovieRecommendationsSimilar(movieId, Constants.ENDPOINT_SIMILAR) Request
API <[#blue]- MovieAPI: ( getMovieRecommendationsSimilar(movieId, Constants.ENDPOINT_SIMILAR) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie/{movieId}/similar) Response(List<Movie>)
User -[#red]> API: ( /movie/actor) Request(actor1,actor2)
end
group service
API -[#red]> MovieAPI: ( movieService.getMoviesWithActors(actor1, actor2)) Request
API <[#blue]- MovieAPI: ( movieService.getMoviesWithActors(actor1, actor2)) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie/actor) Response(List<Movie>)
User -[#red]> API: ( /movie/{movieId}/director) Request(movieId)
end
group service
API -[#red]> MovieAPI: ( getDirectorByMovie(movieId)) Request
API <[#blue]- MovieAPI: ( getDirectorByMovie(movieId)) Response (Director)
end

group controller
User <[#blue]- API: ( /movie/{movieId}/director) Response(Director)
User -[#red]> API: ( /movie/genrelist) Request()
end
group service
API -[#red]> MovieAPI: ( getGenreList() ) Request
API <[#blue]- MovieAPI: ( getGenreList() ) Response (List<Genres>))
end


group controller
User <[#blue]- API: ( /movie/genrelist) Response(List<Genres>)
User -[#red]> API: ( /{movieId}) Request(movieId)
end
group service
API -[#red]> MovieAPI: ( getMovieById(movieId)) Request(movieId)
API <[#blue]- MovieAPI: ( getMovieById(movieId)) Response (Movie))
end


group controller
User <[#blue]- API: ( /movie/{movieId}) Response(Movie)
User -[#red]> API: ( /movie/popularMovies) Request()
end
group service
API -[#red]> MovieAPI: ( getMovies(Constants.ENDPOINT_POPULAR)) Request
API <[#blue]- MovieAPI: ( getMovies(Constants.ENDPOINT_POPULAR)) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie//popularMovies) Response(List<Movie>)
User -[#red]> API: ( /movie/topRatedMovies) Request()
end
group service
API -[#red]> MovieAPI: ( getMovies(Constants.ENDPOINT_TOP_RATED)) Request
API <[#blue]- MovieAPI: ( getMovies(Constants.ENDPOINT_TOP_RATED)) Response (List<Movie>))
end


group controller
User <[#blue]- API: ( movie/topRatedMovies) Response(List<Movie>)
User -[#red]> API: ( /movie/latestMovie) Request()
end
group service
API -[#red]> MovieAPI: ( getLatestMovie()) Request
API <[#blue]- MovieAPI: ( getLatestMovie()) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie/latestMovie) Response(List<Movie>)
User -[#red]> API: ( /movie/{movieId}/actors) Request(movieId)
end
group service
API -[#red]> MovieAPI: ( getActorsByMovieId(movieId)) Request
API <[#blue]- MovieAPI: ( getActorsByMovieId(movieId)) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie/{movieId}/actors) Response(List<Movie>)
User -[#red]> API: ( /movie/rating) Request(rateMin,rateMax)
end
group service
API -[#red]> MovieAPI: ( getMoviesWithinRating(rateMin, rateMax)) Request
API <[#blue]- MovieAPI: ( getMoviesWithinRating(rateMin, rateMax)) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie/rating) Response(List<Movie>)
User -[#red]> API: ( /movie/random) Request*(
end
group service
API -[#red]> MovieAPI: ( getRandomMovie()) Request
API <[#blue]- MovieAPI: ( getRandomMovie()) Response (Movie))
end


group controller
User <[#blue]- API: ( /movie/random) Response(Movie)
User -[#red]> API: ( /movie/findMovies) Request(from_date,genre,rating,time_available)
end
group service
API -[#red]> MovieAPI: ( getMoviesWithParameters(parameterMap)) Request
API <[#blue]- MovieAPI: ( getMoviesWithParameters(parameterMap)) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /movie/movie/findMovies) Response(List<Movie>)
User -[#red]> API: ( /movie/upcoming) Request(region)
end
group service
API -[#red]> MovieAPI: ( getUpcomingMovies(region)) Request
API <[#blue]- MovieAPI: ( getUpcomingMovies(region)) Response (List<Movie>))
end


group controller
User <[#blue]- API: ( /movie/upcoming) Response(List<Movie>)
'End Movie
'Start Actor
User -[#red]> API: ( /actor/{actorId}) Request(actorId)
end
group service
API -[#red]> MovieAPI: ( getActor(actorId)) Request
API <[#blue]- MovieAPI: ( getActor(actorId)) Response (Actor)
end

group controller
User <[#blue]- API: ( /actor/{actorId}) Response(Actor)
User -[#red]> API: ( /actor/popular) Request()
end
group service
API -[#red]> MovieAPI: ( getPopularActors()) Request
API <[#blue]- MovieAPI: ( getPopularActors()) Response (List<Actor>))
end

group controller
User <[#blue]- API: ( /actor/popular) Response(List<Actor>)
'End Actor

'Start MovieReviewController
User -[#red]> API: ( /movie/{id}/reviews) Request(id)
end
group service
API -[#red]> MovieAPI: ( getReviewsByMovieId(id)) Request
API <[#blue]- MovieAPI: ( getReviewsByMovieId(id)) Response (List<MovieReviews>)
end

group controller
User <[#blue]- API: ( /movie/{id}/reviews) Response(List<MovieReviews>)
'End MovieReviewController

'Start Search
User -[#red]> API: ( /search/movie/{searchTerm}) Request(searchTerm)
end
group service
API -[#red]> MovieAPI: ( searchMovies(searchTerm)) Request
API <[#blue]- MovieAPI: ( searchMovies(searchTerm)) Response (List<Movie>))
end

group controller
User <[#blue]- API: ( /search/movie/{searchTerm}) Response(List<Movie>)
User -[#red]> API: ( /search/actor/{searchTerm}) Request(searchTerm)
end
group service
API -[#red]> MovieAPI: ( searchActor(searchTerm)) Request
API <[#blue]- MovieAPI: ( searchActor(searchTerm)) Response (<List<Actor>)
end

group controller
User <[#blue]- API: ( /search/actor/{searchTerm}) Response(<List<Actor>)

end
User -[#red]> API: ( /actuator/health) Request(searchTerm)
User <[#blue]- API: ( /actuator/health) Response(Status:UP)



@enduml