@startuml


package controller <<Folder>> #lime{

    class controllerMovie{
    -ola
    +good
    }

}


package model <<Folder>> #burlywood{

  class movie{
  +Hi
  }

}

package repository <<Folder>> #violet {

  interface movieRepository {
  +Hi
  }

}

package service <<Folder>> #red{

  interface movieService{
  +Hi
  }
  class movieServiceImpl{
  +Hi
  }

}

@enduml